name: jlr_flutter_portfolio
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^8.1.1
  cloud_firestore: ^4.7.0
  equatable: ^2.0.5
  file_saver: ^0.2.2
  firebase_core: ^2.12.0
  firebase_storage: ^11.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_chat_bubble: ^2.0.2
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.4
  intl: any
  provider: ^6.0.5
  universal_html: ^2.2.1
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
